In [4]:
import numpy as np
print(np.__version__)

2.3.4


In [1]:
lst=[10,20,30,40,55]
print("Given List\n",lst)
print("Data Type=",type(lst))

Given List
 [10, 20, 30, 40, 55]
Data Type= <class 'list'>


In [7]:
lst1=np.array(lst)
print(lst1)
print("Data Type=",type(lst1))

[10 20 30 40 55]
Data Type= <class 'numpy.ndarray'>


In [8]:
lst=[10,20,30,40]
lst2=np.array(lst)
print(lst2)

[10 20 30 40]


In [9]:
lst=np.array([10,20,30])
print(lst)
print("Data Type of List is = ",type(lst))

[10 20 30]
Data Type of List is =  <class 'numpy.ndarray'>


Approaches to Create An Object of Ndarray of Numpy

In [10]:
#Array
l1=[10,20,30,40,50,79]
print(l1,type(l1))
a=np.array(l1)
print(a,type(a))

[10, 20, 30, 40, 50, 79] <class 'list'>
[10 20 30 40 50 79] <class 'numpy.ndarray'>


In [14]:
#Attributes of Array
t=np.array([10,20,30,40,50,60])
print(t)
print("Dimension of Array",t.ndim)
print("Data Type of Array",t.dtype)
print("Size of Array",t.size)
print("Shape of Array",t.shape)
b=t.reshape(2,3)
print(b)


[10 20 30 40 50 60]
Dimension of Array 1
Data Type of Array int64
Size of Array 6
Shape of Array (6,)
[[10 20 30]
 [40 50 60]]


In [15]:
#arange
a=np.arange(10,20)
print(a)

[10 11 12 13 14 15 16 17 18 19]


In [16]:
b=np.arange(10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
b=np.arange(0,20,2)
print(b)

[ 0  2  4  6  8 10 12 14 16 18]


In [18]:
b=np.arange(1,20,2)
print(b)

[ 1  3  5  7  9 11 13 15 17 19]


In [19]:
a=int(input("Enter How many no want:"))
b=np.arange(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
a=int(input("Enter Starting Value:"))
b=int(input("Enter Ending Value:"))
c=np.arange(a,b)
print("Your Values\n",c)

Your Values
 [ 0  1  2  3  4  5  6  7  8  9 10]


In [21]:
a=int(input("Enter Starting Value:"))
b=int(input("Enter Ending Value:"))
c=int(input("Enter Ending Value:"))
d=np.arange(a,b,c)
print("Your Values\n",d)

Your Values
 [ 0  2  4  6  8 10]


In [24]:
try:
  a=int(input("Enter Starting Value:"))
  b=int(input("Enter Ending Value:"))
  c=int(input("Enter Ending Value:"))
  d=np.arange(a,b,c)
  print("Your Values\n",d)
except ValueError as e:
  print("Enter Correct Value",e)

Your Values
 [44 45 46 47 48 49 50 51 52 53 54]


In [25]:
#Zeros
a=int(input("Enter How Many Zeros Want:"))
b=np.zeros(a)
print("Values Are\n",b)

Values Are
 [0. 0. 0. 0. 0.]


In [31]:
size=int(input("Enter How Many Zeros Want:"))
b=np.zeros(size)
print("Values Are\n",b)

Values Are
 [0. 0. 0. 0. 0.]


In [33]:
#ones
a=np.ones(3,dtype=int)
print(a)

[1 1 1]


In [35]:
a=np.ones((2,2))
print(a)

[[1. 1.]
 [1. 1.]]


In [5]:
a=np.zeros(9,dtype=int).reshape(3,3)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [6]:
a=np.ones((4,4),dtype=int)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [7]:
a=np.array([1,2,3,4,5,6])
np.extract(a>2,a)

array([3, 4, 5, 6])

In [8]:
a=np.array([1,2,3,4,5,6])
np.extract(a<2,a)

array([1])

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [1]:
import numpy as np
from numpy import random as r
print(r.randint(100))


38


In [3]:
x=r.randint(10)
print(x)

4


In [4]:
x=r.randint(100,1000)
print(x)

437


In [5]:
x=r.randint(10,20,size=5)
print(x)

[18 10 17 18 16]


In [7]:
x=r.randint(10,20,size=(3,4))
print(x)

[[17 15 12 17]
 [12 14 19 13]
 [10 11 15 19]]


In [8]:
rv=r.rand()
print(rv)

0.7426590401756051


In [9]:
rv=r.rand(5)
print(rv)

[0.50549952 0.95373661 0.90357637 0.30705589 0.76407008]


In [10]:
rv=r.rand(12)
print(rv)

[0.13433731 0.04549152 0.48714926 0.16687484 0.54381063 0.52326701
 0.16241248 0.13299571 0.17129311 0.499924   0.55317856 0.6568475 ]


In [11]:
rv=r.rand(3,3)
print(rv)

[[0.51681923 0.20150599 0.17036277]
 [0.53285974 0.33557901 0.22937043]
 [0.04992848 0.0979493  0.34482089]]


In [12]:
rv=r.rand(3,3,2)
print(rv)

[[[3.72954750e-01 3.52313452e-01]
  [9.37564542e-01 8.32409730e-01]
  [9.33100022e-02 9.54698421e-03]]

 [[6.55195247e-01 1.39275568e-01]
  [6.99951308e-01 7.79526795e-02]
  [6.42163784e-01 1.78803571e-01]]

 [[1.54976155e-04 6.57254197e-01]
  [3.92179866e-01 1.76401308e-01]
  [6.25487270e-01 4.02841122e-01]]]


In [13]:
uv=r.uniform()
print(uv)


0.7023184293822793


In [14]:
uv=r.uniform(5,10)
print(uv)

7.985257130035848


In [15]:
uv=r.uniform(10,11,size=4)
print(uv)

[10.3302784  10.7218855  10.10404065 10.64807478]


In [16]:
uv=r.uniform(10,11,size=(2,3))
print(uv)

[[10.93035043 10.30700491 10.97953055]
 [10.46383293 10.31926276 10.8207165 ]]


In [17]:
uv=r.uniform(10,11,size=(3,3,2))
print(uv)

[[[10.11355219 10.64206994]
  [10.69823818 10.63096393]
  [10.85908718 10.31996095]]

 [[10.84651306 10.89521968]
  [10.53144931 10.27116016]
  [10.82057759 10.38061664]]

 [[10.04498105 10.41375577]
  [10.92558889 10.84286911]
  [10.37824626 10.42221986]]]


In [18]:
rv=r.randn()
print(rv)

0.6501481477359597


In [19]:
rv=r.randn(4)
print(rv)

[-1.25416738 -1.13727173  0.35145075 -0.69328462]


In [20]:
rv=r.randn(3,3)
print(rv)

[[-0.19799532  0.89891361 -0.4520972 ]
 [-0.37679104 -0.49704204 -0.37098951]
 [ 0.88164321  1.13279328  0.13619238]]


In [21]:
rv=r.randn(3,3,2)
print(rv)

[[[ 0.98486315  1.89612292]
  [-0.09706327 -0.62141654]
  [ 0.44819153 -0.3056912 ]]

 [[-0.98112658  0.47870498]
  [-0.22114727  1.37654771]
  [ 0.26651834 -0.49094526]]

 [[-0.26601836 -0.28349593]
  [ 2.01629102 -1.94310334]
  [-0.58583651  1.63536355]]]


In [22]:
rv=r.normal()
print(rv)


-2.4207072836143326


In [23]:
rv=r.normal(2)
print(rv)

-0.5221348463323343


In [24]:
rv=r.normal(2,4)
print(rv)

-1.009124567199045


In [25]:
rv=r.normal(2,3,size=5)
print(rv)

[-0.46025413  2.32495787  2.3098635  -4.27248946  0.88532419]


In [26]:
rv=r.normal(2,3,size=(3,3))
print(rv)

[[-1.14076134  3.52356462  2.07223771]
 [-4.59123024 -1.20243012  0.8238869 ]
 [ 3.35112496 -0.24543261  1.02759807]]


In [27]:
rv=r.normal(2,3,size=(2,3,3))
print(rv)

[[[-8.12393518  0.13930726  3.35128832]
  [ 3.16966308  6.10446578 -0.64509256]
  [ 8.8081112   6.25986919  3.72244338]]

 [[ 8.54186602  3.49339925  2.34119462]
  [ 8.00018498 -1.54748748  5.28078983]
  [-6.53023155  3.61918586 -2.75884284]]]


In [28]:
a=np.array([1,2,3,4,5])
print(a)
cv=r.choice(a)
print(cv)

[1 2 3 4 5]
2
