In [4]:
import numpy as np
print(np.__version__)

2.3.4


In [1]:
lst=[10,20,30,40,55]
print("Given List\n",lst)
print("Data Type=",type(lst))

Given List
 [10, 20, 30, 40, 55]
Data Type= <class 'list'>


In [7]:
lst1=np.array(lst)
print(lst1)
print("Data Type=",type(lst1))

[10 20 30 40 55]
Data Type= <class 'numpy.ndarray'>


In [8]:
lst=[10,20,30,40]
lst2=np.array(lst)
print(lst2)

[10 20 30 40]


In [9]:
lst=np.array([10,20,30])
print(lst)
print("Data Type of List is = ",type(lst))

[10 20 30]
Data Type of List is =  <class 'numpy.ndarray'>


Approaches to Create An Object of Ndarray of Numpy

In [10]:
#Array
l1=[10,20,30,40,50,79]
print(l1,type(l1))
a=np.array(l1)
print(a,type(a))

[10, 20, 30, 40, 50, 79] <class 'list'>
[10 20 30 40 50 79] <class 'numpy.ndarray'>


In [14]:
#Attributes of Array
t=np.array([10,20,30,40,50,60])
print(t)
print("Dimension of Array",t.ndim)
print("Data Type of Array",t.dtype)
print("Size of Array",t.size)
print("Shape of Array",t.shape)
b=t.reshape(2,3)
print(b)


[10 20 30 40 50 60]
Dimension of Array 1
Data Type of Array int64
Size of Array 6
Shape of Array (6,)
[[10 20 30]
 [40 50 60]]


In [15]:
#arange
a=np.arange(10,20)
print(a)

[10 11 12 13 14 15 16 17 18 19]


In [16]:
b=np.arange(10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
b=np.arange(0,20,2)
print(b)

[ 0  2  4  6  8 10 12 14 16 18]


In [18]:
b=np.arange(1,20,2)
print(b)

[ 1  3  5  7  9 11 13 15 17 19]


In [19]:
a=int(input("Enter How many no want:"))
b=np.arange(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
a=int(input("Enter Starting Value:"))
b=int(input("Enter Ending Value:"))
c=np.arange(a,b)
print("Your Values\n",c)

Your Values
 [ 0  1  2  3  4  5  6  7  8  9 10]


In [21]:
a=int(input("Enter Starting Value:"))
b=int(input("Enter Ending Value:"))
c=int(input("Enter Ending Value:"))
d=np.arange(a,b,c)
print("Your Values\n",d)

Your Values
 [ 0  2  4  6  8 10]


In [24]:
try:
  a=int(input("Enter Starting Value:"))
  b=int(input("Enter Ending Value:"))
  c=int(input("Enter Ending Value:"))
  d=np.arange(a,b,c)
  print("Your Values\n",d)
except ValueError as e:
  print("Enter Correct Value",e)

Your Values
 [44 45 46 47 48 49 50 51 52 53 54]


In [25]:
#Zeros
a=int(input("Enter How Many Zeros Want:"))
b=np.zeros(a)
print("Values Are\n",b)

Values Are
 [0. 0. 0. 0. 0.]


In [31]:
size=int(input("Enter How Many Zeros Want:"))
b=np.zeros(size)
print("Values Are\n",b)

Values Are
 [0. 0. 0. 0. 0.]


In [33]:
#ones
a=np.ones(3,dtype=int)
print(a)

[1 1 1]


In [35]:
a=np.ones((2,2))
print(a)

[[1. 1.]
 [1. 1.]]


In [5]:
a=np.zeros(9,dtype=int).reshape(3,3)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [6]:
a=np.ones((4,4),dtype=int)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [7]:
a=np.array([1,2,3,4,5,6])
np.extract(a>2,a)

array([3, 4, 5, 6])

In [8]:
a=np.array([1,2,3,4,5,6])
np.extract(a<2,a)

array([1])